name: muapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  action_slider: ^0.7.0
  haptic_feedback: ^0.4.2
  flutter_card_swiper: ^7.0.1
  geolocator: ^12.0.0
  http: ^1.2.1
  provider: ^6.1.2
  responsive_navigation_bar: ^4.0.4
  flutter_secure_storage: ^8.0.0  # Downgraded to an earlier version
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ig/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 500

dependency_overrides:
  win32: ^5.0.0  # Update to a newer version
  collection: ^1.18.0  # Update to the latest version